# Generated by Django 5.2.5 on 2025-08-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0003_alter_invite_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='resident',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='9HSIVD', max_length=6, unique=True),
        ),
    ]
