# Generated by Django 5.2.5 on 2025-08-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0004_rename_resident_house_user_alter_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='email',
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='VXRR3B', max_length=6, unique=True),
        ),
    ]
